package com.enreach.ssm.dao;

import com.enreach.ssm.entity.Article;
import com.enreach.ssm.entity.example.ArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleMapper {
    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    long countByExample(ArticleExample example);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    int deleteByExample(ArticleExample example);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    int deleteByPrimaryKey(Integer articleId);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    int insert(Article record);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    int insertSelective(Article record);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    Article selectOneByExample(ArticleExample example);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    Article selectOneByExampleWithBLOBs(ArticleExample example);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    List<Article> selectByExampleWithBLOBs(ArticleExample example);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    List<Article> selectByExample(ArticleExample example);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    Article selectByPrimaryKey(Integer articleId);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    Article selectByPrimaryKeyWithLogicalDelete(@Param("articleId") Integer articleId, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    int updateByExampleWithBLOBs(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    int updateByPrimaryKeySelective(Article record);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    int updateByPrimaryKeyWithBLOBs(Article record);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    int updateByPrimaryKey(Article record);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    int logicalDeleteByExample(@Param("example") ArticleExample example);

    /**
    * generated by MyBatis Generator. database table [t_article]
    */
    int logicalDeleteByPrimaryKey(Integer articleId);
}