<?xml version="1.0" encoding="UTF-8"?>
<template>

    <!-- xml 注释 -->
    <comment ID="addComment"><![CDATA[
        <!--
  This element is automatically generated by MyBatis Generator, do not modify.
-->
        ]]>
    </comment>

    <!-- #############################################################################################################
    字段注释
    -->
    <comment ID="addFieldComment"><![CDATA[
<#if introspectedColumn??>

    <#if introspectedColumn.remarks?? && introspectedColumn.remarks != ''>
    /**
        <#list introspectedColumn.remarks?split("\n") as remark>
*   ${remark}
        </#list>
*/
    </#if>

</#if>
        ]]>
    </comment>

    <!-- #############################################################################################################
    类注释
    -->
    <comment ID="addModelClassComment"><![CDATA[

<#if introspectedTable.remarks?? && introspectedTable.remarks != ''>
    <#list introspectedTable.remarks?split("\n") as remark>
 /**  ${remark}  */
    </#list>
</#if>
        ]]>
    </comment>


    <!-- 接口方法注释 -->

    <comment ID="addGeneralMethodComment"><![CDATA[
        /**
* generated by MyBatis Generator. database table [${introspectedTable.fullyQualifiedTable}]
*/
        ]]>
    </comment>


</template>